### ISSUE TITLE
Unable to mirgrate... need help

### ISSUE THREAD

**Issue by utpal2** [jfelder/Laravel-OracleDB#27]
Im facing the [PDOException]
could not find driver error while trying to migrate .. I have already enabled pdo_mysql extension in php.ini file.. but still it is not working plz help me out...im using xampp on ubuntu 14.04 and laravel 4.

**Comment by jfelder** [comment]
This package is for oracle not mysql so you have to either have oracle pdo driver installed or the oci8 library. I would suggest looking up how to get these working on your server. Something like http://stackoverflow.com/a/25728192 may be able to help.
