### ISSUE TITLE
Use it without OCI driver

### ISSUE THREAD

**Issue by alvarotrigo** [jfelder/Laravel-OracleDB#28]
As I can not force the server to contain the TNS files and threfore I believe I have to use this plugin without the OCI driver. 

I'm a bit lost regarding the DB connection and I don't know if this is possible at all with this plugin. 

Could I set a connection string in another way to be able to connect even when the server doesn't contain the TNS files necessary for the oci connection ? 

Right now my TNS looks like so:
```
MYNAME =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.xxx.xxx)(PORT = xxx))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = XXX)
    )
  )
```
Where `xxx` is just a value.

I'm not quite sure which values should be used in the config array:

```php
		'oracle' => array(
			'driver'   => 'pdo',
			'tns'      => '',
			'host'     => '',
			'port'     => '1521',
			'database' => '',
			'username' => '',
			'password' => '',
			'charset'  => 'WE8ISO8859P1',
			'prefix'   => '',
			'quoting'  => false,
		),
```

This is what I have at the moment and it doesn't connect:

```php
 'oracle' => array(
            'driver'   => 'oci',
            'tns'      => '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.xxx.xxx)(PORT = xxx)) ) (CONNECT_DATA = (SERVICE_NAME = xxx) ))',
            'username' =>  'xxx',
            'password' =>  'xxx',
            'prefix'   => '',
        ),
```

**Comment by jfelder** [comment]
I do not use any tns files on the server when using this plugin. What you have looks fine except you need to use "oci8" not "oci" to use the oci library connection string format. 

So replace 
```
'oracle' => array(
            'driver'   => 'oci',
```

with

```
'oracle' => array(
            'driver'   => 'oci8',
```

and see if that works for you. If not let me know.

Jimmy

**Comment by alvarotrigo** [comment]
I found the problem. It was working as expected. 
My mistake.
