### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by krisanalfa** [jfelder/Laravel-OracleDB#33]
When I try your package, this error occurs:

```
Call to undefined function Jfelder\OracleDB\config_path()
```

Btw, I'm using Lumen (5.1.5) (Laravel Components 5.1.*)

**Comment by jfelder** [comment]
I haven't used Lumen yet so I haven't tried this with it but a quick google search showed [this.](https://github.com/GrahamCampbell/Laravel-GitHub/issues/10)
