### ISSUE TITLE
oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by wangxianzhe015** [jfelder/Laravel-OracleDB#34]
I added the following code in composer.json file and run `composer update` command.

    "require": {
        "jfelder/oracledb": "5.1.*"
    },

The following code is `config/oracledb.php` file.

    return [
        'oracle' => [
            'driver'    => 'oci8',
            'tns'       => env('DB_TNS', ''),
            'host'      => env('DB_HOST', '192.168.25.4'),
            'port'      => env('DB_PORT', '1521'),
            'database'  => env('DB_DATABASE', 'mydatabase'),
            'username'  => env('DB_USERNAME', 'sys'),
            'password'  => env('DB_PASSWORD', 'dkflfkd'),
            'charset'   => 'AL32UTF8',
            'prefix'    => '',
            'quoting'   => false,
        ],
    ];

The error is as follows.

    ErrorException in OCI.php line 96:
    oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified

Please help me to fix this error soon.

**Comment by jfelder** [comment]
The way the code works is that it converts 

```php
return [
    'oracle' => [
        'driver'    => 'oci8',
        'tns'       => env('DB_TNS', ''),
        'host'      => env('DB_HOST', '192.168.25.4'),
        'port'      => env('DB_PORT', '1521'),
        'database'  => env('DB_DATABASE', 'mydatabase'),
        'username'  => env('DB_USERNAME', 'sys'),
        'password'  => env('DB_PASSWORD', 'dkflfkd'),
        'charset'   => 'AL32UTF8',
        'prefix'    => '',
        'quoting'   => false,
    ],
];
```

into 

```
(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.25.4)(PORT = 1521))(CONNECT_DATA =(SID = mydatabase)))
```

Do you have a working TNS string that you can use? Basically all I do is plug in the variables to create a tns string so if you have a working tns string, just place that string in the tns parameter and it should also work. I don't see anything work with your config.
