### ISSUE TITLE
Undefined constant 'OCI_COMMIT_ON_SUCCESS'

### ISSUE THREAD

**Issue by mulama77** [jfelder/Laravel-OracleDB#35]
have edited config/oracledb.php i.e 

return [
    'staging' => [
        'driver'    => 'oci8',
        'tns'       => env('DB_TNS', ''),
        'host'      => env('DB_HOST', '192.168.1.5'),
        'port'      => env('DB_PORT', '1521'),
        'database'  => env('DB_DATABASE', 'stagingdb'),
        'username'  => env('DB_USERNAME', 'username'),
        'password'  => env('DB_PASSWORD', 'password'),
        'charset'   => 'WE8ISO8859P1',
        'prefix'    => '',
        'quoting'   => false,
    ],
];

in the controller
 $results = DB::connection('staging')->select('select * from interactive.users');

then i got the below error
PHP Fatal error:  Undefined constant 'OCI_COMMIT_ON_SUCCESS' in /var/www/sample/vendor/jfelder/oracledb/src/Jfelder/OracleDB/Connectors/OracleConnector.php on line 35

line having the above issue is

return new OCI($dsn, $config['username'], $config['password'], $options, $config['charset']);

Has anyone experience the above :(:(:(

**Comment by jfelder** [comment]
This error means that you don't have the OCI library installed or it is not configured correctly. Check your php settings to make sure you have it installed and configured properly. See [here] (http://php.net/manual/en/intro.oci8.php) for more info on OCI. 

If you want to use PDO, then change the driver config to be 'pdo'.
